# Site settings
title: Stellar
subtitle: by HTML5 UP
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url: https://github.com/moodule
facebook_url: https://github.com/moodule
github_url: https://github.com/moodule
gitlab_url: https://github.com/moodule
instagram_url: https://github.com/moodule
linkedin_url: https://github.com/moodule
medium_url: https://github.com/moodule
pinterest_url: https://github.com/moodule
slack_url: https://github.com/moodule
snapchat_url: https://github.com/moodule
twitter_url: https://github.com/moodule

# Optional elements
logo_url: /assets/images/logo.svg
favicon_url: /assets/images/favicon.ico
legal_terms_url: /legal-terms
privacy_policy_url: /privacy-policy

# Collections
collections:
  home_sections:
    output: false
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/jekyll-theme-stellar" # the base hostname & protocol for your site, e.g. http://example.com
author: David Mougeolle

# Exclude from processing
